//! Cross-platform cleanup candidates and scan state.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::time::{SystemTime, UNIX_EPOCH};
use thiserror::Error;

use crate::dashboard::SuggestionRisk;

/// Lifecycle state for a read-only cleanup scan.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ScanStatus {
    /// No scan has been started.
    Idle,
    /// The platform adapter is preparing its allow-listed roots.
    Discovering,
    /// Candidate roots are being measured.
    Scanning,
    /// The scan completed and the result can be previewed.
    Completed,
    /// The scan was cancelled at a safe boundary.
    Cancelled,
    /// The scan failed before producing a trustworthy result.
    Failed,
}

/// Progress and provenance for a read-only scan.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanProgress {
    /// Unique identifier for this scan result.
    pub scan_id: String,
    /// Current lifecycle state.
    pub status: ScanStatus,
    /// Number of filesystem entries inspected.
    pub scanned_items: u64,
    /// Number of entries skipped because they were inaccessible or unsafe.
    pub skipped_items: u64,
    /// Human-readable phase description.
    pub message: String,
    /// Stable source-volume hint captured during discovery.
    pub source_volume_id: Option<String>,
}

/// A user-visible cleanup candidate found by a versioned rule.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CleanupCandidate {
    /// Stable rule-scoped identifier for UI selection.
    pub id: String,
    /// Versioned rule identifier that produced this candidate.
    pub rule_id: String,
    /// Concise display title.
    pub title: String,
    /// Explanation of why the content is considered reclaimable.
    pub description: String,
    /// Allow-listed path discovered by the platform adapter.
    pub path: String,
    /// Bytes that could be reclaimed if this candidate is later approved.
    pub bytes: u64,
    /// Number of files and directories represented by the candidate.
    pub item_count: u64,
    /// Risk classification controlling default selection and confirmation.
    pub risk: SuggestionRisk,
    /// Whether the content can normally be regenerated by its application.
    pub recoverable: bool,
    /// Whether the preview selects this candidate by default.
    pub default_selected: bool,
    /// SHA-256 digest of the discovered file metadata, not file contents.
    pub metadata_digest: String,
    /// Wall-clock time when this candidate was observed, in Unix milliseconds.
    pub observed_at_unix_ms: Option<u64>,
}

/// Complete read-only cleanup preview returned to the UI.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CleanupPreview {
    /// Scan state and completeness information.
    pub scan: ScanProgress,
    /// Candidates grouped by cleanup rule.
    pub candidates: Vec<CleanupCandidate>,
    /// Sum of all candidate sizes, independent of UI selection.
    pub total_reclaimable_bytes: u64,
}

/// Immutable, execution-free cleanup plan generated from one completed scan.
///
/// The plan is deliberately a domain artifact only. It does not authorize a
/// deletion; a future privileged executor must revalidate every snapshot and
/// require a separate user confirmation token.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CleanupPlan {
    /// Stable identifier for this plan instance.
    pub plan_id: String,
    /// Scan identifier from which the plan was derived.
    pub scan_id: String,
    /// Selected candidates copied from the completed preview.
    pub candidates: Vec<CleanupCandidate>,
    /// SHA-256 digest of the canonical plan payload.
    pub plan_digest: String,
    /// Explicitly false until a separately reviewed executor is implemented.
    pub execution_authorized: bool,
    /// Creation time in Unix milliseconds.
    pub created_at_unix_ms: u64,
    /// Hard expiry after which revalidation must fail.
    pub expires_at_unix_ms: u64,
    /// Volume hint from the originating scan.
    pub source_volume_id: Option<String>,
}

/// Lifecycle events retained for a future local audit log.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum AuditEventKind {
    /// A read-only scan completed.
    ScanCompleted,
    /// A non-authorizing plan was generated.
    PlanCreated,
    /// A plan was rejected during revalidation.
    PlanRejected,
}

/// Minimal, privacy-preserving audit record for cleanup safety decisions.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AuditEvent {
    /// Event identifier generated by the caller.
    pub event_id: String,
    /// Event type.
    pub kind: AuditEventKind,
    /// Related scan or plan identifier.
    pub subject_id: String,
    /// Event time in Unix milliseconds.
    pub occurred_at_unix_ms: u64,
    /// Optional safe-to-display reason; never contains file contents.
    pub reason: Option<String>,
}

const PLAN_TTL_MS: u64 = 10 * 60 * 1000;

impl CleanupPlan {
    /// Builds a deterministic, non-authorizing plan from default-selected items.
    ///
    /// # Errors
    ///
    /// Returns an error if the preview is incomplete, contains no selected
    /// items, or its candidate data cannot be serialized for hashing.
    pub fn from_preview(preview: &CleanupPreview) -> Result<Self, CleanupPlanError> {
        if preview.scan.status != ScanStatus::Completed {
            return Err(CleanupPlanError::PreviewNotCompleted {
                status: preview.scan.status,
            });
        }
        let candidates: Vec<_> = preview
            .candidates
            .iter()
            .filter(|candidate| candidate.default_selected)
            .cloned()
            .collect();
        if candidates.is_empty() {
            return Err(CleanupPlanError::NoSelectedCandidates);
        }
        let payload = PlanDigestPayload {
            scan_id: &preview.scan.scan_id,
            candidates: &candidates,
        };
        let encoded = serde_json::to_vec(&payload)
            .map_err(|error| CleanupPlanError::Serialization(error.to_string()))?;
        let digest = Sha256::digest(encoded);
        let plan_digest = digest.iter().map(|byte| format!("{byte:02x}")).collect();

        let created_at_unix_ms = current_unix_ms();
        Ok(Self {
            plan_id: format!("plan-{}", preview.scan.scan_id),
            scan_id: preview.scan.scan_id.clone(),
            candidates,
            plan_digest,
            execution_authorized: false,
            created_at_unix_ms,
            expires_at_unix_ms: created_at_unix_ms.saturating_add(PLAN_TTL_MS),
            source_volume_id: preview.scan.source_volume_id.clone(),
        })
    }

    /// Revalidates this plan against a fresh read-only preview.
    ///
    /// This method never changes files. It rejects stale scan identifiers,
    /// candidate changes, digest changes, or any newly selected rule output.
    pub fn validate_against(&self, preview: &CleanupPreview) -> Result<(), CleanupPlanError> {
        self.validate_against_at(preview, current_unix_ms())
    }

    /// Revalidates using a supplied clock, making expiry behavior testable.
    pub fn validate_against_at(
        &self,
        preview: &CleanupPreview,
        now_unix_ms: u64,
    ) -> Result<(), CleanupPlanError> {
        if preview.scan.status != ScanStatus::Completed {
            return Err(CleanupPlanError::PreviewNotCompleted {
                status: preview.scan.status,
            });
        }
        if self.scan_id != preview.scan.scan_id {
            return Err(CleanupPlanError::ScanIdChanged);
        }
        if now_unix_ms > self.expires_at_unix_ms {
            return Err(CleanupPlanError::PlanExpired);
        }
        if self.source_volume_id != preview.scan.source_volume_id {
            return Err(CleanupPlanError::VolumeChanged);
        }
        let current = Self::from_preview(preview)?;
        if current.plan_digest != self.plan_digest || current.candidates != self.candidates {
            return Err(CleanupPlanError::CandidateChanged);
        }
        Ok(())
    }
}

fn current_unix_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis().try_into().unwrap_or(u64::MAX))
        .unwrap_or(0)
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct PlanDigestPayload<'a> {
    scan_id: &'a str,
    candidates: &'a [CleanupCandidate],
}

impl CleanupPreview {
    /// Creates a validated completed preview from scan output.
    ///
    /// # Errors
    ///
    /// Returns an error when the scan is not complete or the candidate byte
    /// total overflows while being aggregated.
    pub fn completed(
        scan: ScanProgress,
        candidates: Vec<CleanupCandidate>,
    ) -> Result<Self, CleanupError> {
        if scan.status != ScanStatus::Completed {
            return Err(CleanupError::PreviewRequiresCompletedScan {
                status: scan.status,
            });
        }

        let total_reclaimable_bytes = candidates
            .iter()
            .try_fold(0_u64, |total, candidate| total.checked_add(candidate.bytes));

        let Some(total_reclaimable_bytes) = total_reclaimable_bytes else {
            return Err(CleanupError::CandidateBytesOverflow);
        };

        Ok(Self {
            scan,
            candidates,
            total_reclaimable_bytes,
        })
    }
}

/// Validation errors for cleanup previews.
#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum CleanupError {
    /// A preview must never look complete when the scan was cancelled or failed.
    #[error("cleanup preview requires a completed scan, got {status:?}")]
    PreviewRequiresCompletedScan {
        /// Actual scan state.
        status: ScanStatus,
    },
    /// Candidate sizes exceeded the representable byte range.
    #[error("cleanup candidate bytes overflowed while aggregating")]
    CandidateBytesOverflow,
}

/// Errors raised while creating a non-authorizing cleanup plan.
#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum CleanupPlanError {
    /// Plans may only be derived from completed scans.
    #[error("cleanup plan requires a completed scan, got {status:?}")]
    PreviewNotCompleted { status: ScanStatus },
    /// An empty selection cannot produce an actionable review artifact.
    #[error("cleanup plan has no selected candidates")]
    NoSelectedCandidates,
    /// The fresh scan belongs to a different scan session.
    #[error("cleanup plan scan id changed")]
    ScanIdChanged,
    /// One or more candidate snapshots differ from the original plan.
    #[error("cleanup plan candidates changed; a fresh plan is required")]
    CandidateChanged,
    /// The plan exceeded its short review lifetime.
    #[error("cleanup plan expired; a fresh scan is required")]
    PlanExpired,
    /// The source volume changed between scan and revalidation.
    #[error("cleanup plan source volume changed")]
    VolumeChanged,
    /// Candidate data could not be encoded for digesting.
    #[error("cleanup plan could not be serialized: {0}")]
    Serialization(String),
}

#[cfg(test)]
mod tests {
    use super::{CleanupCandidate, CleanupError, CleanupPreview, ScanProgress, ScanStatus};
    use crate::dashboard::SuggestionRisk;

    fn candidate(bytes: u64) -> CleanupCandidate {
        CleanupCandidate {
            id: "browser-cache:chrome".to_owned(),
            rule_id: "browser-cache.v1".to_owned(),
            title: "浏览器缓存".to_owned(),
            description: "可重新生成的缓存内容".to_owned(),
            path: "C:\\Users\\demo\\AppData\\Local\\Google\\Chrome\\Cache".to_owned(),
            bytes,
            item_count: 3,
            risk: SuggestionRisk::Safe,
            recoverable: true,
            default_selected: true,
            metadata_digest: "digest".to_owned(),
            observed_at_unix_ms: Some(1),
        }
    }

    fn completed_scan() -> ScanProgress {
        ScanProgress {
            scan_id: "scan-1".to_owned(),
            status: ScanStatus::Completed,
            scanned_items: 10,
            skipped_items: 1,
            message: "扫描完成".to_owned(),
            source_volume_id: Some("C:".to_owned()),
        }
    }

    #[test]
    fn aggregates_candidate_bytes() {
        let preview =
            CleanupPreview::completed(completed_scan(), vec![candidate(10), candidate(20)])
                .expect("completed scan should produce a preview");

        assert_eq!(preview.total_reclaimable_bytes, 30);
    }

    #[test]
    fn rejects_incomplete_scans() {
        let mut scan = completed_scan();
        scan.status = ScanStatus::Cancelled;

        let error = CleanupPreview::completed(scan, vec![])
            .expect_err("cancelled scan must not produce a completed preview");

        assert_eq!(
            error,
            CleanupError::PreviewRequiresCompletedScan {
                status: ScanStatus::Cancelled,
            }
        );
    }

    #[test]
    fn creates_non_authorizing_deterministic_plan() {
        let preview = CleanupPreview::completed(
            completed_scan(),
            vec![candidate(10), {
                let mut item = candidate(20);
                item.default_selected = false;
                item
            }],
        )
        .expect("completed scan should produce a preview");

        let first = super::CleanupPlan::from_preview(&preview).expect("plan should be valid");
        let second = super::CleanupPlan::from_preview(&preview).expect("plan should be valid");

        assert_eq!(first, second);
        assert_eq!(first.candidates.len(), 1);
        assert!(!first.execution_authorized);
        assert_eq!(first.plan_digest.len(), 64);
        assert!(first.expires_at_unix_ms > first.created_at_unix_ms);
    }

    #[test]
    fn rejects_empty_selection() {
        let mut item = candidate(20);
        item.default_selected = false;
        let preview = CleanupPreview::completed(completed_scan(), vec![item])
            .expect("completed scan should produce a preview");

        assert_eq!(
            super::CleanupPlan::from_preview(&preview),
            Err(super::CleanupPlanError::NoSelectedCandidates)
        );
    }

    #[test]
    fn rejects_changed_candidate_snapshot() {
        let preview = CleanupPreview::completed(completed_scan(), vec![candidate(20)])
            .expect("completed scan should produce a preview");
        let plan = super::CleanupPlan::from_preview(&preview).expect("plan should be valid");
        let mut changed = preview.clone();
        changed.candidates[0].metadata_digest = "changed".to_owned();

        assert_eq!(
            plan.validate_against(&changed),
            Err(super::CleanupPlanError::CandidateChanged)
        );
    }

    #[test]
    fn rejects_expired_plan() {
        let preview = CleanupPreview::completed(completed_scan(), vec![candidate(20)])
            .expect("completed scan should produce a preview");
        let plan = super::CleanupPlan::from_preview(&preview).expect("plan should be valid");

        assert_eq!(
            plan.validate_against_at(&preview, plan.expires_at_unix_ms + 1),
            Err(super::CleanupPlanError::PlanExpired)
        );
    }

    #[test]
    fn audit_event_serializes_without_file_contents() {
        let event = super::AuditEvent {
            event_id: "event-1".to_owned(),
            kind: super::AuditEventKind::PlanCreated,
            subject_id: "plan-scan-1".to_owned(),
            occurred_at_unix_ms: 42,
            reason: Some("仅供复核".to_owned()),
        };
        let json = serde_json::to_string(&event).expect("audit event should serialize");
        assert!(json.contains("planCreated"));
        assert!(!json.contains("C:\\"));
    }
}
