import type { DiskHealthSnapshot, PhysicalDiskHealth } from "@/types/health";

const GIB = 1024 ** 3;

const healthyDisk: PhysicalDiskHealth = {
  id: "disk:fixture-nvme-0",
  number: 0,
  friendlyName: "Samsung NVMe SSD",
  manufacturer: "Samsung",
  model: "MZVL21T0HCLR",
  firmwareVersion: "GXA7601Q",
  serialSuffix: "8K2P",
  busType: "NVMe",
  mediaType: "SSD",
  sizeBytes: 953 * GIB,
  operationalStatus: ["OK"],
  isOffline: false,
  providerHealth: "healthy",
  smartStatus: "passed",
  identityMapping: "exact",
  temperatureCelsius: 38,
  temperatureMaxCelsius: 51,
  wearPercentUsed: 7,
  estimatedLifeRemainingPercent: 93,
  powerOnHours: 2_486,
  readErrorsTotal: 0,
  readErrorsUncorrected: 0,
  writeErrorsTotal: 0,
  writeErrorsUncorrected: 0,
  logicalSectorBytes: 512,
  physicalSectorBytes: 4096,
  encryption: {
    protectedVolumes: 1,
    unprotectedVolumes: 1,
    unknownVolumes: 0,
  },
  dataCompleteness: "complete",
  status: "good",
  signals: [],
  partitionWritesBlocked: true,
};

const attentionDisk: PhysicalDiskHealth = {
  id: "disk:fixture-sata-1",
  number: 1,
  friendlyName: "Backup SATA HDD",
  manufacturer: "Western Digital",
  model: "WD40EZAZ",
  firmwareVersion: "80.00A80",
  serialSuffix: "4M7D",
  busType: "SATA",
  mediaType: "HDD",
  sizeBytes: 3726 * GIB,
  operationalStatus: ["OK"],
  isOffline: false,
  providerHealth: "warning",
  smartStatus: "warning",
  identityMapping: "diskNumber",
  temperatureCelsius: 62,
  temperatureMaxCelsius: 64,
  wearPercentUsed: null,
  estimatedLifeRemainingPercent: null,
  powerOnHours: 18_942,
  readErrorsTotal: 4,
  readErrorsUncorrected: 0,
  writeErrorsTotal: 0,
  writeErrorsUncorrected: 0,
  logicalSectorBytes: 512,
  physicalSectorBytes: 4096,
  encryption: {
    protectedVolumes: 0,
    unprotectedVolumes: 1,
    unknownVolumes: 0,
  },
  dataCompleteness: "complete",
  status: "attention",
  signals: [
    {
      code: "providerWarning",
      severity: "warning",
      title: "存储提供程序需要注意",
      detail: "Windows 返回 Warning 状态。",
      recommendation: "尽快备份并观察健康状态是否继续变化。",
    },
    {
      code: "temperatureHigh",
      severity: "warning",
      title: "磁盘温度偏高",
      detail: "当前温度为 62°C，达到 60°C 提醒阈值。",
      recommendation: "检查风道和持续负载，并继续观察温度。",
    },
    {
      code: "correctedErrors",
      severity: "warning",
      title: "存在已纠正或重试错误",
      detail: "可靠性计数累计报告 4 次读写错误。",
      recommendation: "继续监控错误计数变化，并确保备份可用。",
    },
  ],
  partitionWritesBlocked: true,
};

/** Browser-only health data for visual development without physical-disk access. */
export const diskHealthFixture: Readonly<DiskHealthSnapshot> = {
  capturedAtUnixMs: Date.now(),
  disks: [healthyDisk, attentionDisk],
  summary: {
    totalDisks: 2,
    goodDisks: 1,
    attentionDisks: 1,
    criticalDisks: 0,
    unknownDisks: 0,
    overallStatus: "attention",
  },
  discoveryWarnings: [],
  readOnly: true,
};
